name: 纯Windows CMD 构建 x64+arm64
on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: 拉取仓库文件
        uses: actions/checkout@v4

      # 彻底解锁PowerShell执行策略
      - name: 彻底解锁PS执行策略
        run: |
          powershell "Set-ExecutionPolicy Bypass -Scope LocalMachine -Force"
          powershell "Set-ExecutionPolicy Bypass -Scope CurrentUser -Force"
          powershell "Set-ExecutionPolicy Bypass -Scope Process -Force"

      # 开启长路径支持
      - name: 适配Windows系统环境
        run: |
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f

      # ========== X64 流程 ==========
      - name: 解压x64文件夹内ZIP压缩包
        run: |
          cd /d "%GITHUB_WORKSPACE%\x64"
          for %%a in (*.zip) do tar -xf "%%a"

      - name: 运行原版uup cmd
        run: |
          cd /d "%GITHUB_WORKSPACE%\x64"
          uup_download_windows.cmd

      - name: ISO自动加架构版本重命名
        run: |
          cd /d "%GITHUB_WORKSPACE%\x64"
          for %%f in (*.iso) do (
            set "name=%%~nxf"
            setlocal enabledelayedexpansion
            ren "%%f" "Windows_x64_!name!"
            endlocal
          )

      - name: 上传X64镜像
        uses: actions/upload-artifact@v4
        with:
          name: Windows_x64
          path: x64\*.iso

      # ========== ARM64 流程 ==========
      - name: 解压arm64文件夹内ZIP压缩包
        run: |
          cd /d "%GITHUB_WORKSPACE%\arm64"
          for %%a in (*.zip) do tar -xf "%%a"

      - name: 运行原版uup cmd
        run: |
          cd /d "%GITHUB_WORKSPACE%\arm64"
          uup_download_windows.cmd

      - name: ISO自动加架构版本重命名
        run: |
          cd /d "%GITHUB_WORKSPACE%\arm64"
          for %%f in (*.iso) do (
            set "name=%%~nxf"
            setlocal enabledelayedexpansion
            ren "%%f" "Windows_arm64_!name!"
            endlocal
          )

      - name: 上传ARM64镜像
        uses: actions/upload-artifact@v4
        with:
          name: Windows_arm64
          path: arm64\*.iso
