name: RemoteChrome
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Chrome
        run: choco install googlechrome -y

      - name: Start Chrome
        run: |
          $p = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          $arg = "--headless=new --remote-debugging-port=9222 --remote-allow-origins=* --disable-gpu"
          Start-Process $p $arg

      - name: Wait
        run: Start-Sleep 20

      - name: Start Tunnel
        run: |
          choco install cloudflared -y
          cloudflared tunnel --url http://127.0.0.1:9222 --no-host-header
