name: CF_UUP
on: workflow_dispatch
permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Install
        run: choco install googlechrome cloudflared -y

      - name: Launch Chrome
        run: start /b chrome.exe --remote-debugging-port=9222 --remote-debugging-password=123456 --disable-gpu https://uupdump.net

      - name: Launch Cloudflare Tunnel
        run: cloudflared tunnel --url http://127.0.0.1:9222
