name: Chrome9222
on: workflow_dispatch

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: 安装必备
        run: choco install googlechrome cloudflared -y

      - name: 启动Chrome 9222端口
        run: |
          $path = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          $arg = "--remote-debugging-port=9222 --remote-allow-origins=* --disable-gpu --headless=new"
          Start-Process $path $arg

      - name: 等待启动
        run: Start-Sleep -Seconds 10

      - name: 启动隧道 ✅ 解决 Host 报错
        run: cloudflared tunnel --url http://127.0.0.1:9222 **--origin-server-name localhost**
